### PR TITLE
Option for disabling the rect

### PR DESCRIPTION
**Pull request by mohammedzamakhan**

### CODE REVIEW

**Comment by w8r** [comment]
Thanks a lot! Did you check the case when it's shown/hidden using `setOptions`?

**Comment by mohammedzamakhan** [comment]
@w8r no I didn’t. Will try and let you know

**Comment by mohammedzamakhan** [comment]
@w8r yes it works with setOptions too

**Comment by w8r** [comment]
I think it's much easier to suppress it by doing 
```js
layer.transform({
  boundsOptions: { 
    opacity: 0,        // transparent
    interactive: false // all events fall through
  }
});
```
But thank you for your PR!

**Pull request closed without merging**
